### PR TITLE
Merging work from job, profile, and user branches

### PR DESCRIPTION
**Pull request by bgordenBU**

### CODE REVIEW

**Comment by brennama** [comment]
When I clicked on the user profile page I got an error - see screenshot. 
Screenshot 2024-02-19 at 10 49 03 PM

**Comment by bgordenBU** [comment]
@brennama You have to re-run the database script `php artisan migrate:refresh --seed`

Sorry I should have made that clear.

**Comment by brennama** [comment]
Yep that fixed it, thanks!

**Review by brennama — APPROVED** [review]
Looks great!

**Pull request merged**
